In [2]:
import numpy as np

In [29]:
import numpy as np

def calculate(items) :
    if len(items) != 9 :
        raise ValueError('List must contain nine numbers.')
    Arr = np.array(items) 
    Arr = Arr.reshape(3,3) 
    keys = ['mean','variance','standard deviation','max','min','sum']
    output_dict = {key : [] for key in keys} 
    output_dict['mean'].extend([Arr.mean(axis=0).tolist(),Arr.mean(axis=1).tolist(),float(Arr.mean())])
    output_dict['variance'].extend([Arr.var(axis=0).tolist(),Arr.var(axis=1).tolist(),float(Arr.var())])
    output_dict['standard deviation'].extend([Arr.std(axis=0).tolist(),Arr.std(axis=1).tolist(),float(Arr.std())]) 
    output_dict['max'].extend([Arr.max(axis=0).tolist(),Arr.max(axis=1).tolist(),float(Arr.max())]) 
    output_dict['min'].extend([Arr.min(axis=0).tolist(),Arr.min(axis=1).tolist(),float(Arr.min())]) 
    output_dict['sum'].extend([Arr.sum(axis=0).tolist(),Arr.sum(axis=1).tolist(),float(Arr.sum())]) 
    return output_dict




{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8.0], 'min': [[0, 1, 2], [0, 3, 6], 0.0], 'sum': [[9, 12, 15], [3, 12, 21], 36.0]}


float

[[0 1 2] 
 [3 4 5] 
 [6 7 8]]